import Head from 'next/head'
import { Inter } from '@next/font/google'
import Navbar from '@/components/Navbar'
import FeaturedPost from '@/components/FeaturedPost'
import CardPost from '@/components/CardPost'
import { useState } from 'react'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [posts, setPosts] = useState([
    {
      thumbnail: '/thumbnail-2.png',
      category: 'Internet',
      date: '8 Feb 2023',
      title: 'Title of Blog',
      shortDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum optio similique odit perspiciatis alias, nesciunt fuga architecto omnis doloribus autem.',
      authorName: 'M. Fahrur Rizal'
    },
    {
      thumbnail: '/thumbnail-4.png',
      category: 'Internet',
      date: '8 Feb 2023',
      title: 'Title of Blog',
      shortDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum optio similique odit perspiciatis alias, nesciunt fuga architecto omnis doloribus autem.',
      authorName: 'M. Fahrur Rizal'
    },
    {
      thumbnail: '/thumbnail-3.png',
      category: 'Internet',
      date: '8 Feb 2023',
      title: 'Title of Blog',
      shortDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum optio similique odit perspiciatis alias, nesciunt fuga architecto omnis doloribus autem.',
      authorName: 'M. Fahrur Rizal'
    },
    {
      thumbnail: '/thumbnail-3.png',
      category: 'Internet',
      date: '8 Feb 2023',
      title: 'Title of Blog',
      shortDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum optio similique odit perspiciatis alias, nesciunt fuga architecto omnis doloribus autem.',
      authorName: 'M. Fahrur Rizal'
    },
    {
      thumbnail: '/thumbnail-3.png',
      category: 'Internet',
      date: '8 Feb 2023',
      title: 'Title of Blog',
      shortDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum optio similique odit perspiciatis alias, nesciunt fuga architecto omnis doloribus autem.',
      authorName: 'M. Fahrur Rizal'
    },
  ])

  return (
    <>
      <Head>
        <title>{process.env.appName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-900 text-gray-50 min-h-screen'>
        <div className='flex flex-col'>
          <Navbar />

          <div className="container">
            <FeaturedPost />
            <div className='grid grid-cols-3 gap-8 my-8'>
            {posts.map((post, i) => (
              <CardPost key={i} {...post} />
            ))}
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
