import Head from 'next/head';
import FeaturedPost from '@/components/FeaturedPost';
import Posts from '@/components/Posts';
import RootLayout from '@/components/layouts/RootLayout';

export default function Home() {
  return (
    <>
      <Head>
        <title>{process.env.appName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <RootLayout>
          <FeaturedPost />
          <Posts />
        </RootLayout>
      </main>
    </>
  );
}
